coinbase/coinbase-pro-node

lib/clients/websocket.js
The current websocket API does not require requests to be signed.
Since `self.auth` is always defined via a default object, I tested whether to sign the request by checking `self.auth.secret` with the assumption that `self.auth.key` and `self.auth.passphrase` could not be undefined if `self.auth.secret` is defined.
fixes #17
=> fix: Sign websocket 'subscribe' only if auth is given

lib/orderbook_sync.js, tests/orderbook_sync_test.js
`Gdax.OrderbookSync` inherits from `Gdax.WebsocketClient`. It should therefore emit the same messages on the same events.
The `open`, `close`, and `error` events had not been overriden, but `message` has. This restores it.
=> lib/orderbook_sync: emit 'message' event

README.md, lib/clients/authenticated.js, package.json, tests/authenticated.js
Adds methods, tests, & README for the new margin related endpoints:
https://docs.gdax.com/#list-fundings
https://docs.gdax.com/#repay
https://docs.gdax.com/#margin-transfer
https://docs.gdax.com/#close
=> Add methods for margin endpoints

CHANGELOG.md, README.md, lib/clients/websocket.js, lib/orderbook_sync.js, lib/utilities.js, tests/authenticated.js, tests/orderbook.js, tests/orderbook_sync_test.js, tests/public_client.js
This is a non-backwards-compatible change since `OrderbookSync` no longer has a `book` property; it now has `books`.
See README.md change:
```
-var orderbookSync = new Gdax.OrderbookSync();
-console.log(orderbookSync.book.state());
+var orderbookSync = new Gdax.OrderbookSync(['BTC-USD', 'ETH-USD']);
+console.log(orderbookSync.books['ETH-USD'].state());
```
=> OrderbookSync: Multiple books

package.json
What Node versions does this npm module support?
I might be wrong, but I'm guessing >= 4. The reason is [Node 0.10, 0.11 and 0.12 have reached end-of-life.](https://github.com/nodejs/LTS#lts-schedule)
=> add engines config

package.json
Fix for #64 and #59, caused by lagging WS and bufferUtil mismatch.
100% test coverage for Node LTS v6.11.0
=> [DEPS] Upgrade WS to latest stable version.

lib/orderbook_sync.js
The orderbook sync issue happens when the initial loadOrderbook finishes before the websocket client has subscribed to any products, which will cause some initial updates to be missed. This can also cause several unnecessary resyncs. Waiting until after the first message for that product is received resolved the issue (#62, #80) in my testing. A setTimeout for several seconds on the initial loadOrderbook call works most of the time as well, but it is not guaranteed.
=> Delayed initial orderbook sync until first message is received (#62).

lib/orderbook_sync.js, tests/orderbook_sync.spec.js
It will be interesting to have the ability to listen to authenticated WebSocket when authenticated client is provided. What do you guys think?
=> OrderbookSync uses authenticated websocket

lib/orderbook.js
Asks in 0.4.2 were using `each` but in this version they are using `reach`.  Thus causing them to be backwards.
=> fix(asks): They were in wrong order.

lib/clients/public.js
This way it is possible to make calls like:
AuthenticatedClient.getOrders({ status: ['open', 'done'] });
Previously it caused signature errors as arrays were formatted
with indices.
=> Configured array formatting in request extra parameters to 'repeat'

README.md, lib/clients/authenticated.js, package.json, tests/authenticated.spec.js
The use of the `/transfers` route has been deprecated for some time. Instead we should be using the routes specifically for coinbase [deposits](https://docs.gdax.com/#coinbase) and [withdrawals](https://docs.gdax.com/#coinbase54).
Note: This change is not backwards compatible as the `currency` must now be defined as well.
=> remove use of deprecated /transfers route

lib/clients/authenticated.js, lib/clients/public.js
The response is currently only included in callbacks and dropped in Promise requests.
This PR attaches the response to the error object in rejected promises.
=> Include response in promise rejections

README.md, index.d.ts, lib/clients/authenticated.js, lib/orderbook_sync.js
This more consistent usage allows an `AuthenticatedClient` instance to be used
in place of an `auth` object thereby simplifying codebase and general usage patterns.
`AuthenticatedClient` used to have a `b64secret` property, but all auth object credentials expected a `secret` property. By making the two consistent, we gain better consistency, and the codebase can be simplified a bit.
**Other considerations**
This will likely need to be rebased after #150 is merged.
=> Refactor auth object to { key, secret, passphrase }

lib/clients/websocket.js, lib/orderbook_sync.js, lib/utilities.js, tests/orderbook_sync.spec.js
This is a direct follow-up to https://github.com/coinbase/gdax-node/pull/151#issuecomment-348232843
- Adds a `checkAuth()`  utility function to ensure an `auth` object contains `key`, `secret`, and `passphrase`
- Simplifies `OrderbookSync` constructor to take auth object instead of a full `AuthenticatedClient` instance
This is still backwards compatible with the old constructor signature, because `AuthenticatedClient` has the same `key`, `secret`, and `passphrase` properties.
/cc @fb55
=> Simplify OrderbookSync constructor signature

index.d.ts, lib/clients/websocket.js, lib/orderbook_sync.js, tests/websocket.spec.js
- Automatically adds the `heartbeat` channel if not already subscribed
- Removes redundant `keepalive` ping on the socket
Fixes #113
=> Fix heartbeat channel subscriptions

README.md, index.d.ts, lib/clients/authenticated.js, lib/clients/public.js, lib/orderbook_sync.js, tests/authenticated.spec.js, tests/public_client.spec.js
- **Deprecates `productID` argument in `PublicClient` constructor**
- Requires `productID` as first argument to `getProductOrderBook()` and deprecates old usage signature
- Removes redundant `AuthenticatedClient#getProductOrderBook()` override
- Simplifies `OrderbookSync#loadOrderbook()` because both clients now adhere to the same method signature
- Requires `productID` as first argument to `getProductTicker()` and deprecates old usage signature
- Requires `productID` as first argument to `getProductTrades()` and deprecates old usage signature
- Requires `productID` as first argument to `getProductTradeStream()` and deprecates old usage signature
- Requires `productID` as first argument to `getProductHistoricRates()` and deprecates old usage signature
- Requires `productID` as first …
=> Normalize PublicClient with AuthenticatedClient 

README.md
**Extracted from PR #83**
- Disclaimers are already covered by the official MIT LICENSE
- Semantic versioning isn't a feature; it's an expectation of all good software libraries. 
/cc @fb55
=> Remove disclaimers from README

.gitignore, circle.yml
- Adds `yarn.lock` and `.node-version` to `.gitignore` (two common tools that people use, but the config files don't belong in the repository for a shared library)
- Updates `circle.yml` to rely on latest Node v6 LTS version (v6.12.2)
/cc @fb55
=> Update gitignore and CircleCI node version

index.d.ts
This was done to silence the ts compiler with strict type checks enabled.
It is just a temporary solution, type definitions should contain few (ideally none) `any` types, hopefully, someone who knows what the correct types are will define them properly and replace this quick fix.
=> Added explicit any types to all untyped code

lib/clients/authenticated.js, lib/clients/public.js, package.json, tests/public_client.spec.js
`request` doesn't have a default timeout set. 
If GDAX API servers time out, the connection will stay open and the callbacks for HTTP requests will never be called leaving requests in limbo.
This PR adds a default timeout of 10s to all requests and adds an option to set the value in the constructor.
=> Add a default timeout to each request

lib/clients/websocket.js, tests/orderbook_sync.spec.js, tests/websocket.spec.js
Before, if an `error` message is sent from the server, that error is emitted as regular `message` data. Now, if a message of `type=error` arrives, it is emitted as an `error` instead.
Also removes auto-incrementing port for testing websocket server connections. We got to a point where we ran into port conflicts on the CI server.
- FIxes #219
/cc @fb55
=> Emit error when websocket message is an error

README.md
The value '3000' is not an acceptable input for the granularity parameter of getProductHistoricRates. From the [API documentation](https://docs.gdax.com/#get-historic-rates):
> The granularity field must be one of the following values: {60, 300, 900, 3600, 21600, 86400}. Otherwise, your request will be rejected.
=> Change granularity parameter in README to an acceptable input.

lib/clients/authenticated.js, lib/clients/public.js, tests/authenticated.spec.js, tests/public_client.spec.js
- Fixes error handling expectations as documented in #208
- Non-2xx HTTP status codes will now (correctly) return an error
- Fixes #208
- Closes #209 (this PR is stacked on top of that one, but this one adds tests and fixes extra edge cases)
=> Fix request error handling

lib/request_signer.js, lib/utilities.js
Results in the following error if credentials are missing before signing a request:
```
Error: Invalid or incomplete authentication credentials. Please provide all of the key, secret, and passphrase fields.
```
Closes #232
/cc @fb55
=> Improve error handling by checking auth before every signature

README.md
Otherwise the master branch always has to be spotless.
=> Remove github install instructions from README

package.json
Fixes mistake in `precommit` setup. `eslint` cannot be run on json or markdown.
Ref #235
/cc @fb55
=> Fix precommit: eslint cannot be run on json or markdown

lib/orderbook_sync.js, tests/orderbook_sync.spec.js
I got tired of seeing the following warning in the test suite:
```
(node:59176) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Failed to load orderbook: whoops
```
Turned out that simplifying the code behind grabbing the initial Orderbook did the trick.
I think this fixes #233 
/cc @fb55
=> Fix UnhandledPromiseRejectionWarning in OrderbookSync

package.json, tests/websocket.spec.js
- Upgrades and relaxes core dependencies. Static versions are ill-advised for shared libraries, because clients cannot take advantage of 3rd party bug fixes and performance improvements. Let semver do its thing.
- Upgrades mocha and nock dev dependencies. This actually exposed an errant test connection in test suite.
- Closes out the errant websocket server in test suite.
/cc @fb55 
Aside, much of ~#239~ (now merged) and ~#240~ (now merged) was discovered while trying to work on this.
=> Upgrade and relax dependencies

README.md, lib/clients/websocket.js, lib/orderbook_sync.js, tests/websocket.spec.js
- This PR is stacked on top of @fuzzyTew's PR #179.
- Instead of a stateful `Websocket#[un]subscribeProduct()` and `#[un]subscribeChannel()`, the changes here simplify the method signatures down to just a stateless `#subscribe()` and `#unsubscribe()` that is a direct pass through to the GDAX API.
- These new method signatures match the [GDAX API `subscribe`/`unsubscribe` messages](https://docs.gdax.com/#subscribe) directly.
- Closes #179 
```javascript
websocket.unsubscribe({ channels: ['full'] });
websocket.subscribe({ product_ids: ['LTC-USD'], channels: ['ticker', 'user'] });
websocket.subscribe({
channels: [{
name: 'user',
product_ids: ['ETH-USD']
}]
});
websocket.unsubscribe({
channels: [{
name: 'user',
product_ids: ['LTC-USD']
}, {
name: 'user',
product_ids: ['ETH-USD']
}]
});
```
=> Add Websocket#subscribe() and #unsubscribe()

lib/orderbook.js, package.json
I was loading a lot of a data and noticed that the `num` library was slow. I gave `decimal.js` a shot and it's significantly faster.
=> Faster decimal library.

README.md
Websocket Client example call should use a wss endpoint, not the rest endpoint.
=> corrected README.md Websocket Client example to use wss endpoint

lib/orderbook.js, tests/orderbook.spec.js
Fixes #255.  A null price can be returned from the API on a change request, when this happens in indicates that the order was a market order.  The problem currently is that there is no check to ensure that the price is not null, and passing a null price to BigNumber will cause an uncaught exception.
> Any change message where the price is null indicates that the change message is for a market order. Change messages for limit orders will always have a price specified.
[Relevant GDAX API docs](https://docs.gdax.com/#the-code-classprettyprintfullcode-channel)
=> Check for null price on change request

README.md
"Your callback should accept **two** arguments:" but then three are listed.  This addresses the inconsistency.
=> Arg count fix in readme

index.d.ts
The ability to place stop limit orders is not documented as described in issue #164. While it's still possible to place a stop limit when directly interfacing with the gdax-node library it is not possible when using the gdax-tt due to the typescript declaration limitations. I am extending the BaseOrder interface declaration as per the [GDAX API Reference](https://docs.gdax.com/#place-a-new-order). This will enable the necessary changes to be made on the gdax-tt project to also support stop limit orders.
=> Add typings for stop limit orders

index.d.ts
DELETE /orders/${id} always returns a list of order IDs, even when
deleting a single order.
=> index.d.ts: cancelOrder() returns a list of order IDs.

lib/clients/public.js
This is for consistency between the different ways an Error instance
is created and populated.
=> When a request fails, always set the data property.

index.d.ts
Make the args argument required, but make its product_id property
optional, so it's still easy to not set it.
index.d.ts(225,56): error TS1016: A required parameter cannot follow an optional parameter.
=> Fix cancelAllOrders compile error.

index.d.ts
Fix for issue: https://github.com/coinbase/gdax-node/issues/306
=> Add pageArgs to the getProductTrades definition

index.d.ts
Quick fix to add BCH to the CurrencyType (Issue: https://github.com/coinbase/gdax-node/issues/310)
=> Add BCH to CurrencyType

.circleci/config.yml, circle.yml, lib/orderbook.js, lib/orderbook_sync.js, package-lock.json, package.json, tests/authenticated.spec.js, tests/orderbook_sync.spec.js, tests/websocket.spec.js
- Adds CircleCI build matrix (with node v6, v8, v10)
- Switched to CircleCI version 2
- Also runs a `lint` and `prettier` sanity test prior to running the standard test suite (for people who might disable the `precommit` hooks while using `lint-staged`).
- Also fixes existing prettier errors
- Also fixes build on Node 6 (timing and `ECONNRESET` issues) on `OrderbookSync` and `WebsocketClient`
- `prettier` is only run against `*.js` files, because different npm versions mess with package.json & package-lock.json differently (causing the build to unnecessarily fail on different versions).
- Closes #249
/cc @fb55
=> CircleCI Build Matrix

README.md, lib/clients/authenticated.js, tests/authenticated.spec.js
The current authenticated client does not support depositing funds from a payment method.  
The deposit command wraps the /deposits/coinbase-account for moving funds between coinbase accounts. In order to initiate a transfer a call to /deposits/coinbase-account is needed.
=> Add depositPayment method to support /deposits/payment-method

package-lock.json, package.json, tests/authenticated.spec.js
Redo of #323.
It was necessary to better freeze version of `prettier` so that the build can run more consistently across node and npm versions. 
Also updated the package-lock.json based on Node 8/npm 5.
=> Fix build and test dependencies

index.d.ts
Updates the `FillFilter` type so `getFills` will not complain when trying to provide an `order_id` parameter. This mirrors the functionality in the API - https://docs.pro.coinbase.com/#list-fills
=> Fixes #196 - add optional order_id param to getFills type

index.d.ts
These typedefs are more accurate. I based them on these orders:
submission result:
```json
{
"id": "9b335af9-3290-4f52-9d95-6e1e90b61299",
"price": "0.01000000",
"size": "0.01000000",
"product_id": "ETH-BTC",
"side": "buy",
"stp": "dc",
"type": "limit",
"time_in_force": "GTC",
"post_only": false,
"created_at": "2018-04-07T19:58:09.868061Z",
"fill_fees": "0.0000000000000000",
"filled_size": "0.00000000",
"executed_value": "0.0000000000000000",
"status": "pending",
"settled": false
}
```
status response:
```json
{
"id": "9b335af9-3290-4f52-9d95-6e1e90b61299",
"price": "0.01000000",
"size": "0.01000000",
"product_id": "ETH-BTC",
"side": "buy",
"type": "limit",
"time_in_force": "GTC",
"post_only": false,
"created_at": "2018-04-07T19:58:09.868061Z",
"fill_fees": "0.0000000000000000", …
```
=> fix type definitions for new order and order status responses
