README.md, package.json
We have some vulnerable packages that need updating.
Also added an npm script in the README to scan for CVEs in the future.
=> Update vulnerable packages

README.md, lib/clients/authenticated.js
Adding support for the new trailing volume endpoint which can be used to estimate the fee rebates.
Documentation is here: https://docs.gdax.com/#user-account
=> lib/clients/authenticated: Add trailing volume getter

lib/clients/authenticated.js, lib/clients/websocket.js, lib/request_signer.js, package.json
This will allow users to receive user-specific messages on the websocket feed in future
=> Add authentication for websocket feed

lib/clients/websocket.js, tests/lib/ws_testserver.js, tests/websocket.js
Add tests for the WebsocketClient module.
=> Enable connecting to multiple products per WS connection

README.md
Add a comment in the readme to make it obvious that you can connect to the sandbox.
=> Add a comment in the readme.

lib/clients/authenticated.js
A little housekeeping - Cleans up the lib/clients/authenticated.js file.
=> Remove unused import and fix redeclared error variable

README.md
An attempt to deflect some recurring questions.
closes https://github.com/coinbase/gdax-node/issues/51 & https://github.com/coinbase/gdax-node/issues/20
=> docs(readme): clarify init of public client w/ product

.gitignore, lib/clients/authenticated.js, tests/authenticated.spec.js
Added report request and report status
=> Added report request

README.md
w  c(..)o   (
\__(-)    __)
/\   (
/(_)___)
w /|
| \
=> Distinguished the Optional Parameters

lib/clients/websocket.js, package.json, tests/websocket.spec.js
Allow clients to subscribe to channels
=> Add channels

index.d.ts
=> Updated typing for PublicClient constrctor

index.d.ts
* Include optional url parameter in PublicClient constructor
* Add `ProductInfo` interface
* Add B2X currency
=> Some TS definition improvements

README.md, lib/clients/authenticated.js
https://docs.gdax.com/#payment-methods
=> add getPaymentMethods to api calls

README.md, index.d.ts, lib/clients/authenticated.js, tests/authenticated.spec.js
=> Expose AuthenticatedClient#placeOrder() function

index.d.ts
=> Fix BaseOrderInfo's types

index.d.ts
Fix type Account
Extend getOrders/getFills signature to accept props beyond pageargs
(see #231)
=> Fix types inconsistencies

README.md, lib/clients/authenticated.js, tests/authenticated.spec.js
This function can be used to fetch transfers done in an account. Useful in fetching txHash of a transfer made.
=> Add a function to fetch transfers in the account

index.d.ts
...by making it extend PublicClient
=> Fix AuthenticatedClient's type definition

index.d.ts
This adds the name and optional stack properties.
=> HttpError extends Error.

CHANGELOG.md
- Points Changelog at [GitHub Releases](https://github.com/coinbase/gdax-node/releases)
**More importantly**:
- I also backdated some git tags and documented the past few releases to NPM for everything newer than v0.5.0.
**https://github.com/coinbase/gdax-node/releases**
- Closes #317 
/cc @fb55
=> Point Changelog at GitHub Releases

package.json, tests/websocket.spec.js
- Upgrades dev dependencies
- Fixes a websocket test
- Removes README.md from prettier purview -- Different combinations of node/npm/prettier versions  would cause unnecessary build failures and unnecessary markdown format thrashing.
=> Fix build matrix

README.md, lib/clients/authenticated.js, tests/authenticated.spec.js
This adds the ability to withdraw to a payment method -- a complement to the recent https://github.com/coinbase/gdax-node/pull/314
----
Edit by @rmm5t:
- Closes #30
=> Add payment method withdrawal functionality

index.d.ts
Quick fix to add ETC to the CurrencyType. (Issue #331)
=> Add ETC to CurrencyType

lib/clients/websocket.js
Fix connect() and disconnect() behaviour (#226)
=> Fix connect() and disconnect() behaviour (#226)

index.d.ts
and run prettier on the TypeScript definition file.
=> Improve websocket types

lib/clients/websocket.js, tests/websocket.spec.js
and only add heartbeat channel if no channels are specified.
=> Consider websocket `CLOSING` state

.circleci/config.yml, lib/clients/authenticated.js, package.json, tests/authenticated.spec.js, tests/orderbook_sync.spec.js, tests/public_client.spec.js
and set the minimum node version to 8 (required by ws module)
=> Bump dependencies
